spring.application.name=rag

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.model.embedding.text=google-genai
spring.ai.google.genai.embedding.text.options.dimensions=768
spring.datasource.url=jdbc:postgresql://localhost:5432/rag_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768